format = """\
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#EC916D)\
$git_branch\
$git_status\
[](fg:#EC916D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$crystal\
$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
$container\
[](fg:#06969A)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ﲾ ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[container]
symbol = " "
style = "bg:#06969A bold"
format = '[[ $symbol ](bg:#06969A)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A bold"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[git_branch]
symbol = ""
style = "bg:#DC815D bold"
format = '[[ $symbol $branch ](bg:#EC916D)]($style)'

[git_status]
style = "bg:#EC916D bold"
format = '[[($all_status$ahead_behind )](bg:#EC916D)]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[crystal]
symbol = ""
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[python]
symbol = ""
style = "bg:#86BBD8 bold"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A bold"
format = '[[ ♥ $time ](bg:#33658A)]($style)'

